/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacienteshcmodule.vista;
import pacienteshcmodule.DAO.ResultadosDAO; // Asegúrate de importar tu DAO
import java.util.Map;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author USUARIO
 */
public class resultados extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(resultados.class.getName());
    private int idCita;

    /**
     * Creates new form resultados
     */
    public resultados(int idCita) {
    initComponents();
    this.jTAdiagnostico.enableInputMethods(false);
    this.idCita = idCita;
    this.setLocationRelativeTo(null);
    
    // Carga los datos después de que la UI esté lista
    javax.swing.SwingUtilities.invokeLater(() -> {
        cargarTodosLosResultados();
    });
}
private void cargarTodosLosResultados() {
    
    
    // --- Cargar Campos de Texto ---
    
    // 1. Cargar Diagnóstico
    String diagnostico = ResultadosDAO.obtenerDiagnostico(this.idCita);
    this.jTAdiagnostico.setText(diagnostico);
    this.jTAdiagnostico.setComponentOrientation(java.awt.ComponentOrientation.LEFT_TO_RIGHT);
   SwingUtilities.invokeLater(() -> {
    // Primero coloca el caret al inicio del texto
    jTAdiagnostico.setCaretPosition(0);
    
    // Luego ajusta el scroll horizontal a la posición mínima (izquierda)
    JScrollBar horizontal = jScrollPane4.getHorizontalScrollBar();
    horizontal.setValue(horizontal.getMinimum());
    
    // Fuerza una actualización de la UI si es necesario
    jTAdiagnostico.revalidate();
    jTAdiagnostico.repaint();
});

    // 2. Cargar Tratamiento
    String tratamientos = ResultadosDAO.obtenerTratamientos(this.idCita);
    this.jTFTraramiento.setText(tratamientos); // Se usa 'jTFTraramiento' como en tu captura
    System.out.println(tratamientos);

    // 3. Cargar el campo de texto "Resultados"
    String resultadosGenerales = ResultadosDAO.obtenerResultadosGenerales(this.idCita);
    this.jTFResultados.setText(resultadosGenerales);
    System.out.println(resultadosGenerales);


    // --- Cargar Tablas ---

    // 4. Cargar la tabla de exámenes realizados
    this.jTExamenes.setModel(ResultadosDAO.obtenerExamenes(this.idCita));
    
    // 5. Cargar la tabla de la receta enviada
    this.jTReceta.setModel(ResultadosDAO.obtenerReceta(this.idCita));

    // 6. Cargar la tabla de signos vitales
    this.jTSignos.setModel(ResultadosDAO.obtenerSignosVitales(this.idCita));
}

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTFTraramiento = new javax.swing.JTextField();
        jTFResultados = new javax.swing.JTextField();
        jbregresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTExamenes = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTReceta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTSignos = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTAdiagnostico = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTFTraramiento.setEditable(false);
        jTFTraramiento.setText("Descripción del tratamiento");
        jTFTraramiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Tratamiento"));

        jTFResultados.setEditable(false);
        jTFResultados.setText("Descripción de resultados");
        jTFResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jbregresar.setText("Regresar");
        jbregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbregresarActionPerformed(evt);
            }
        });

        jTExamenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Dermatoscopia", "Benigno"},
                {null, null}
            },
            new String [] {
                "Examen", "Resultado"
            }
        ));
        jScrollPane2.setViewportView(jTExamenes);

        jTReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Paracetamol", " 500 gr", "8 horas", "2 semanas", "Pastilla", "16/06/2025"},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Medicamento", "Dosis", "Frecuencia", "Durante", "Presentación", "Fecha de inicio"
            }
        ));
        jScrollPane1.setViewportView(jTReceta);

        jLabel1.setText("Receta enviada");

        jLabel2.setText("Exámenes realizados");

        jLabel3.setText("Signos vitales");

        jTSignos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Presión sistólica", "Presión diastólica", "Peso", "Estatura", "F.C", "Oxigenación"
            }
        ));
        jScrollPane3.setViewportView(jTSignos);

        jTAdiagnostico.setEditable(false);
        jTAdiagnostico.setColumns(20);
        jTAdiagnostico.setRows(5);
        jTAdiagnostico.setTabSize(30);
        jTAdiagnostico.setAlignmentX(0.0F);
        jTAdiagnostico.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagnóstico"));
        jTAdiagnostico.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTAdiagnostico.setDragEnabled(true);
        jTAdiagnostico.setRequestFocusEnabled(false);
        jScrollPane4.setViewportView(jTAdiagnostico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jbregresar)
                .addContainerGap(1181, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTFResultados, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFTraramiento, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFTraramiento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jbregresar)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbregresarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbregresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        int idCitaSeleccionada = 0;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new resultados(idCitaSeleccionada).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTAdiagnostico;
    private javax.swing.JTable jTExamenes;
    private javax.swing.JTextField jTFResultados;
    private javax.swing.JTextField jTFTraramiento;
    private javax.swing.JTable jTReceta;
    private javax.swing.JTable jTSignos;
    private javax.swing.JButton jbregresar;
    // End of variables declaration//GEN-END:variables
}
